name: Generate Clash Rule Provider
on:
  workflow_dispatch:
  push:
    paths:
      - 'config初始.json'
      - 'input.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Clash rule provider
        uses: lazebird/tvconfig_formatter-action@main
        with:
          config_path: config初始.json
          output_path: output/site.yaml
          format: clash

      - name: Generate Omnibox configuration
        uses: lazebird/tvconfig_formatter-action@main
        with:
          config_path: input.json
          output_path: output/omnibox.yaml
          format: omnibox
          
      - name: Commit and push changes
        run: |
          mkdir -p output
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*
          git commit -m "chore: update output/ via test workflow [skip ci]" || echo "No changes to commit"
          git push
